### ISSUE TITLE
Testnet: rough plan proposal

### ISSUE THREAD

**Issue by skozin** [lidofinance/lido-dao#111]
#### Sprint 1, Nov 7—Nov 11

- Deploy Aragon DAO to Goerli with a test governance committee
- Setup a cloud instance with IPFS and Aragon UI
- Determine what CLIs, scripts, and instructions are required (e.g. CLI for a validator to add keys)
- Try running an oracle instance, pointing it to sb else's validators
- Run a test validator node, making a deposit and joining the Medalla Activation Queue

#### Sprint 2, Nov 12—Nov 19

- Deploy latest contract implementations, upgrade the DAO
- Implement missing CLIs, if any
- Prepare the instructions
- Prepare the general test plan document

#### Sprint 3, Nov 20—Nov 25

- Deploy latest contract implementations, upgrade the DAO
- Run an internal test with all actors, according to the general test plan
- Test an emergency stop
- Test other failure modes, e.g. failing oracle nodes
- Deploy another DAO that will be used in the final testing

#### Questions

- Are we going to run test BLS generation ceremony?
- Are we going to upload our code to Etherscan and validate it?
- Do we want external oracle operators during the test?

**Comment by ujenjt** [comment]
Closed
