### ISSUE TITLE
App UIs are not updated until page is refreshed

### ISSUE THREAD

**Issue by skozin** [lidofinance/lido-dao#150]
An example (assumes that voting quorum is 2, as in the current testnet setup):

1. As a DAO holder, go to the Lido app and set the fee to a different value; wait until the TX succeeds. This will start voting.
2. Go to the Voting app, vote for the fee change. Wait until the TX succeeds.
3. Switch Metamask account to another DAO holder, reload the page.
4. Vote for the fee change, wait until the TX succeeds and the vote is enacted.
5. Switch to the Lido app. The old fee value is still displayed.
6. Switch back and forth between apps — it won't help to display the updated fee.
7. Reload the page — only at this moment, the value is updated.

The same goes for other values in Lido, Oracle, and Node Operators apps (e.g. staking limit in Node Operators Registry is not updated after the vote is enacted).

**Comment by azat-s** [comment]
I have subscribed to relevant events in both Lido and Node Operators Registry, so this issue should be resolved. At least, I can't replicate it. E.g. #178
