### ISSUE TITLE
LidoOracle contract: reportable epochs interval may become inverted

### ISSUE THREAD

**Issue by skozin** [lidofinance/lido-dao#176]
The following is possible with the current implementation:

![image](https://user-images.githubusercontent.com/1699593/100024333-98e13480-2df7-11eb-97d0-1100e831f0de.png)

This is caused by the fact that, currently, the earliest reportable epoch is set to the first epoch of the next frame when any of the current frame's epochs become finalized. At the same time, the last reportable epoch is always the current epoch — which can (and, most of the time, will) be less than the first epoch of the next frame.

An example (assuming `epochsPerFrame=100`): current epoch is `10`; oracles agree on the epoch `0`, frame `0` becomes finalized. At this point, `getCurrentReportableEpochs` will return `firstReportableEpochId=100, lastReportableEpochId=10`.

**Comment by ongrid** [comment]
This is mostly cosmetic issue. These numbers shouldn't be interpreted as a range, they should be considered as separate values for the separate checks. 

Note: Nevertheless we need more expressive approach possible with default solidity (non-experimental) ABI encoder like retrieval of all the oracle needs within the single call (still human readable). The sequence of reportable frames with all the metadata is good to have, but it's non-trivial with v0.4.24 encoder. We'd like to have something like this:

```
oracle.getReportableFrames()

[
{epoch: 0, frame: 0, quorum: 5, voted: 4, start: 1234567, end: 1234567, pushed: False, voted: ['0xdeadbeef', '0xbeefdead']},
{epoch: 225, frame: 1, quorum: 5, voted: 0, start: 1234567, end: 1234567, pushed: False, voted: []},
]

```

But it changes the interface so breaks compatibility - so it's the candidate for 0.3.0.

**Comment by ongrid** [comment]
I'd suggest to remove it from the Mainnet launch scope and postpone to v0.3.0 with another breaking changes. I think, we'll deprecate these individual getters and provide the oracle precomputed array of all the values it needs. Still subject to research ABI encoders and check if experimental mode suits here (it's not a bleeding edge, but it was experimental in 0.4.24).

**Comment by ongrid** [comment]
It should be a bit less annoying with the new names for these entities introduced in #215

minReportableEpochId
maxReportableEpochId

and should be deprecated by #230
