### ISSUE TITLE
Migrate from Buidler to Hardhat

### ISSUE THREAD

**Issue by skozin** [lidofinance/lido-dao#202]
Hardhat is the new version of Buidler (they've decided to rename it) that offers a lot of improvements:

* Much faster compilation due to using native `solc` binaries (on our project it looks like a 15x speedup).
* Support of multiple `solc` versions per one configuration (no more multiple config files and `x.y.z` subdirectories under contracts and tests).
* Much better Etherscan verification.
* Mainnet forking.

The main obstacle right now is the `@aragon/buidler-aragon` plugin which wasn't updated yet to support the new version; I've opened an issue: https://github.com/aragon/buidler-aragon/issues/197. That said, the migration doesn't seem too complicated so we could contribute if the Aragon team has no time for it.

You can look at the current state of work in #203, I've started this as a part of Etherscan verification process since it's so much faster and easier with Hardhat.

**Comment by Aveesh52** [comment]
Should I do it?

**Comment by 0xGabi** [comment]
Hey @Aveesh52 I was one of the core developers working on `buidler-aragon` plugin. At 1hive we will be working on update this plugin to hardhat. Maybe we can sync and work together on it?

**Comment by skozin** [comment]
Hey @Aveesh52 and @0xGabi, thanks a lot for offering your help!

The current state is the following:

* We've created [an issue in buidler-aragon](https://github.com/aragon/buidler-aragon/issues/197) couple of months ago, but received no feedback yet.
* We've actually migrated to hardhat and implemented [a custom script](https://github.com/lidofinance/lido-dao/blob/master/scripts/multisig/04-publish-app-frontends.js) to publish Aragon app frontends. It's based on the original `buidler-aragon` code, uses its internal APIs, and [fixes the issue](https://github.com/lidofinance/lido-dao/blob/master/scripts/multisig/04-publish-app-frontends.js#L109) with parsing Solidity code targeted for newer compiler version (hardhat supports using multiple compiler versions in the same project).

Our team's been really busy lately with the work on the protocol and various integrations, so I'm not sure we'll be able to dedicate a significant effort to updating the plugin. We'll be more than happy to discuss the scope of the required changes and share our thoughts, though. We can do it here, but also feel free to join our [Discord dev channel](https://discord.com/channels/761182643269795850/773584934619185154) and ping me (`skozin#0633`).

**Comment by 0xGabi** [comment]
Sharing my answer here as well: https://github.com/aragon/buidler-aragon/issues/197#issuecomment-841701637

**Comment by vshvsh** [comment]
@skozin

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by TheDZhon** [comment]
Resolved with #426.
