### ISSUE TITLE
Increase smart contract test coverage

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#224]
Current smart contract unit tests have less-than-100% test coverage, with some reachable code regions which could be covered.

**Comment by ongrid** [comment]
Modules least covered by tests are Node Operators, their caching and rewards distribution. They are covered by linear "happy-path" tests and it's the maximum we can achieve with this approach. On the calls we discussed should we refactor them to fully-fledged hierarchical test suites (like LidoOracle and tokens) to test against different inputs and conditions. Collectively decided to keep the tests simple and flat for better maintainability and readability. But it still seems to me that hierarchical tests are more than appropriate here.

@skozin @vshvsh @ujenjt @krogla @Eenae Let's look at this question again and decide should we go deeper with testing or leave just plain success-path tests.

**Comment by Eenae** [comment]
Not sure I know what hierarchical tests are, anyway, tests should consider various inputs, various call combinations, and should make sure that the intended behavior is allowed and nothing more (using `assertThrows`).
