### ISSUE TITLE
Deposits fail when the Node Operator with id 0 is deactivated

### ISSUE THREAD

**Issue by skozin** [lidofinance/lido-dao#227]
Steps to reproduce:

1. Add two Node Operators, add keys for each of them.
2. Deactivate the operator with the index `0`.
3. Submit 32 Ether to the pool and try to make a deposit.

#### Expected result

The deposit tx succeeds, a key of the operator with the index `1` is used.

#### Actual result

The deposit tx reverts with the reason `MATH_SUB_UNDERFLOW`.

---

Failing test added in 9cceafa.
Fixed in 44626e2.

**Comment by ujenjt** [comment]
Fixed in #226
