### ISSUE TITLE
LID-10 Precision loss in node operators fee calculation

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#241]
The node operator’s fee is specified in current Lido implementation (`v0.2.0-rc.0`) in a variable number of 1/10000 points. The implementation has multiple integer divisions involving the fee variable and `10000` number, which causes precision loss and makes for unnecessary truncation.
The audit suggests changing the implementation to avoid `div(10000)` operations until later. Namely, calculate the `sharesToMint` value as `(feeBasis * totalRewards * prevTotalShares) / ((10000 * newTotalPooledEther) * (feeBasis * totalRewards) )`

**Comment by skozin** [comment]
Fixed in #236.
