### ISSUE TITLE
LID-16 Potential gas saving optimisation in Memutils.memcpy

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#242]
The audit has detected potential gas saving optimisation in the `Memutils.memcpy` method. Current implementation uses `EXP` operation (Memutils.sol:36), which in this case could be replaced with a cheaper `SHL` call.
Current implementation reads:
`let mask := sub(exp(256, sub(32, _len)), 1) // 2 ** (8 * (32 - _len)) - 1`
Which could be changed to:
`let mask := sub(shl(1, mul(8, sub(32, _len))), 1) // 2 ** (8 * (32 - _len)) - 1`

**Comment by ujenjt** [comment]
Fixed in #239
