### ISSUE TITLE
LID-07 Lido smart contract isn’t ready to receive deposits right after deployment

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#243]
Current (`v0.2.0-rc.0`) implementation doesn't follow some of the Aragon app guides. Namely, it's possible to call state changing methods of `Lido` contract implementation directly on the implementation, and not the proxy wired as an Aragon app. This creates the possibility for malicious actors: if they guide users to, say, call `submit` directly on implementation, their funds would be locked forever. While the audit assesses the risk to be low, it's better to protect the implementation.

**Comment by skozin** [comment]
Fixed in #253.
