### ISSUE TITLE
LID-11 Unintentional funds submitted to the Lido smart contract could be locked

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#244]
Current (`v0.2.0-rc.0`) Lido smart contract fallback function treats any call as funds submission. If the user mistakes Lido for some other contract, they could get their funds locked. To prevent this, the audit proposes to add a `require(msg.data.length == 0);` statement to the fallback function.

**Comment by skozin** [comment]
Fixed in #238.
