### ISSUE TITLE
LID-17 Potential gas savings in NodeOperatorsRegistry.assignNextSigningKeys method

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#245]
The audit proposes modification of the `NodeOperatorsRegistry.assignNextSigningKeys` method to implement gas savings. The loop at 336 line iterates through the whole cache, but could break when condition `numLoadedKeys == numAssignedKeys` is met, so the method call doesn’t require gas for extra operations.

**Comment by ujenjt** [comment]
Fixed in #239
