### ISSUE TITLE
pre-mainnet review: LidoOracle

### ISSUE THREAD

**Issue by Eenae** [lidofinance/lido-dao#248]
- [x] **error** https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/oracle/LidoOracle.sol#L155-L161

`_member`'s data might be in epochs other than `lastReportedEpochId`, namely, in any epoch in `getCurrentReportableEpochs()`. This data must be discarded as well. The simplest solution is to discard current `gatheredEpochData` altogether. Alternatively, `MIN_REPORTABLE_EPOCH_ID_VALUE_POSITION` may be set to `getCurrentEpochId()` and member data removal may be performed for that epoch.

- [x] **error** https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/oracle/LidoOracle.sol#L187

Why is the comparison strict rather than non-strict? The comparison can be omitted altogether since an epoch without reports has a zero as `reportsBitMask`. That makes finalization impossible.

- [x] **error** https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/oracle/LidoOracle.sol#L188

The assignment is futile since the local variable `minReportableEpochId` is not used afterwards.

- [x] warning https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/oracle/LidoOracle.sol#L214

Because of the reasons mentioned above it makes no sense to track this value.

- [x] comment https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/oracle/LidoOracle.sol#L101-L104

Copy-pasted from `setBeaconSpec`. It makes sense to move the checks to `_setBeaconSpec`.

**Comment by lxzrv** [comment]
1. Members data for all epochs since lastReportedEpochId in getCurrentReportableEpochs() is empty. That's the reason why i discard data before lastReportedEpochId only. MB that is overkill and there is no need to correct bits in lastReportedEpochId and discard it too.
2. Will be fixed
3. Will be fixed
4. ?
5. Fixed

**Comment by ujenjt** [comment]
Take a look on this scenario related to the first error:
https://github.com/lidofinance/lido-dao/pull/259/files#diff-117f4a8edc29f8871be3f39f57e7b4811eba58f42730e413ed57f35706dd05b5R38

**Comment by ujenjt** [comment]
The same issue found by Quantstamp #260

**Comment by lxzrv** [comment]
1, 4: lastReportedEpochId renamed to maxReportedEpochId to avoid confusing (maxReportedEpochId can not be decreased)

**Comment by Eenae** [comment]
Merging https://github.com/lidofinance/lido-dao/pull/257 & https://github.com/lidofinance/lido-dao/pull/259 will close this issue.
