### ISSUE TITLE
pre-mainnet review: Lido

### ISSUE THREAD

**Issue by Eenae** [lidofinance/lido-dao#251]
- [x] warning https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/Lido.sol#L447

The emitted event will have a zero value since `getPooledEthByShares(deposit)` is still zero at this moment.

- [ ] warning https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/Lido.sol#L442-L443

Precision loss during `sharesAmount` computation may be mistaken as the zero pooled ether situation.
Consider an exagerated situation when 1 unit of share equals 1e9 units of ether. Sending a 0.999 gwei deposit will result in `sharesAmount == 0` yielding `true`, `_mintShares(sender, 0.999 gwei)` will be executed. This will result in net profit `0.999e9 * 1e9 - 1e9 - tx_fee` which is much more than `1e9 + tx_fee` ether paid.

I suggest replacing the `sharesAmount` check with an explicit one checking `0 == _getTotalPooledEther()`.

- [ ] comment https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/Lido.sol#L423
https://github.com/lidofinance/lido-dao/blob/ad4b2f634850e46375bf5c8717abf0e49cdce3be/contracts/0.4.24/Lido.sol#L428

I suggest adding `isContract` checks.

**Comment by ujenjt** [comment]
1) is fixed in #236 pull request, also this issue is mentioned in #240.
2) this is good to have, but not a critical one, the fact that that addresses is contracts should be validate off-chain while DAO voting.
