### ISSUE TITLE
`isContract` class isn't used in `LidoOracle.sol`

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#252]
`LidoOracle` contract inherits `isContract` Aragon class, but don't seem to use its only method `isContract`. It seems like the class could be removed from the `LidoOracle`.

`isContract` implementation could be checked here: https://github.com/aragon/aragonOS/blob/next/contracts/common/IsContract.sol

**Comment by skozin** [comment]
Fixed in #254.
