### ISSUE TITLE
Lido: recoverToVault() works with invalid token address

### ISSUE THREAD

**Issue by lxzrv** [lidofinance/lido-dao#258]
Aragon safeMath transfer() does not return false when we try to recover tokens with invalid address (non-contract). MB we should add isContract() check for argument address or another check.
Line with issue: [Lido.sol L307](https://github.com/lidofinance/lido-dao/blob/f0f927c9ca46b4906ad8c815fe568c24b3e0023a/contracts/0.4.24/Lido.sol#L307)
Test case for this here: [commit](https://github.com/lidofinance/lido-dao/commit/f0f927c9ca46b4906ad8c815fe568c24b3e0023a)

**Comment by ujenjt** [comment]
There is no risk here, because transferToVault takes token address as argument.
