### ISSUE TITLE
QSP-14 removeOracleMember() does not clear the last update

### ISSUE THREAD

**Issue by kadmil** [lidofinance/lido-dao#260]
As per audit comment: "`removeOracleMember()` only disables the bitmask and does not update the reports stored in `gatheredEpochData[lastReportedEpochId].reports`."

We're supposing that the Oracles we are about to remove report something wrong. During investigation of the comment we've found cases where such report could have real-life effect.

**Comment by Eenae** [comment]
Hmm. The bitmask is the key. A reports from some member won't be included unless has the bit set. I'm not sure quantstamp guys get the mechanic right.
Although there are some other issues described in #248 .

**Comment by ujenjt** [comment]
@Eenae yes member report won't be included, but previous report just already saved there and will be taking in account during next epoch finalization. Please take a look on this situation https://github.com/lidofinance/lido-dao/pull/259/files#diff-117f4a8edc29f8871be3f39f57e7b4811eba58f42730e413ed57f35706dd05b5R38

**Comment by Eenae** [comment]
I was wrong, thats also a bug. Approved the PR.
