### ISSUE TITLE
Relax checks for live deployment

### ISSUE THREAD

**Issue by banteg** [lidofinance/lido-dao#272]
It would still be useful to run check `12-check-dao.js` script against a live deployment.

Currently it fails because some votes have already kicked off.

I suggest adding an option to run relaxed checks.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/4562643/102560074-68cd3e80-40e2-11eb-8fcd-098442c8c8e2.png">

**Comment by skozin** [comment]
Yeah, that's a good idea. Prob it makes sense to make it configurable.

**Comment by skozin** [comment]
@banteg here you go: https://github.com/lidofinance/lido-dao/pull/276 :)

**Comment by ujenjt** [comment]
Looks like it fixed 🙌
