### ISSUE TITLE
E2E tests revamp

### ISSUE THREAD

**Issue by vshvsh** [lidofinance/lido-dao#278]
Current e2e tests basically go as follows "what if we deployed everything from scratch and then tried a few typical things of lido lifecycle"? 

That is a correct scenario for what we had at the time. But now that lido is deployed, it does no longer serve its purpose. What we need to test now is:

"what if we upgrade current deployed code with a new implementation and then tried a few typical lifecycle things?" 

I think that would remove a lot of complexity from e2e tests and make for a more readable scenarios, plus it would allow to test for integrations if needed.

On the other hand, it'd be much harder to test beacon chain integration bc we'd need to maintan a beacon chain fork; I think our best bet now would be to mock it.

**Comment by vshvsh** [comment]
It can be rather easily done with mainnet-fork environment of ganache or brownie (via ganache).

**Comment by ujenjt** [comment]
Done
