### ISSUE TITLE
Allow oracles members under quorum count

### ISSUE THREAD

**Issue by vshvsh** [lidofinance/lido-dao#284]
The most likely reason for removing an oracle member is a malicious oracle. It's better to have an oracle with no quorum (members can be added or quorum lowered) than an oracle with a quorum but a malicious member in it. 

https://github.com/lidofinance/lido-dao/blob/f177e015d721929db6e66d4803b43382a7135d09/contracts/0.4.24/oracle/LidoOracle.sol#L137 <- we can safely remove that line.

**Comment by vshvsh** [comment]
can remove this
https://github.com/lidofinance/lido-dao/blob/f177e015d721929db6e66d4803b43382a7135d09/contracts/0.4.24/oracle/LidoOracle.sol#L167 
and that too
https://github.com/lidofinance/lido-dao/blob/f177e015d721929db6e66d4803b43382a7135d09/contracts/0.4.24/oracle/LidoOracle.sol#L124

**Comment by dechjo** [comment]
> and that too
> https://github.com/lidofinance/lido-dao/blob/f177e015d721929db6e66d4803b43382a7135d09/contracts/0.4.24/oracle/LidoOracle.sol#L124
Do you mean here, that we explicitly set `quorum` via voting and nothing else can change it?

**Comment by dechjo** [comment]
The change is here: dechjo#3.
Note that this pull request will merge to dechjo/oracle-v2 branch, when approved. I made it so for ease or reviewing.

**Comment by vshvsh** [comment]
> and that too
> 
> https://github.com/lidofinance/lido-dao/blob/f177e015d721929db6e66d4803b43382a7135d09/contracts/0.4.24/oracle/LidoOracle.sol#L124
> 
> 
> Do you mean here, that we explicitly set `quorum` via voting and nothing else can change it?

yes

**Comment by dechjo** [comment]
Pull request is here: https://github.com/lidofinance/lido-dao/pull/294.
