### ISSUE TITLE
Add state change events to oracle functions

### ISSUE THREAD

**Issue by vshvsh** [lidofinance/lido-dao#285]
Not all state changes in oracle are accompanied by the events.

In `reportBeacon(uint256 _epochId, uint128 _beaconBalance, uint128 _beaconValidators)` we should emit an event with all that data and `msg.sender` as well, to make oracle state fully reconstructible by events.

`MIN_REPORTABLE_EPOCH_ID` changes in `removeOracleMember` and `setQuorum` should emit an event about that too.

**Comment by dechjo** [comment]
The change is here: https://github.com/dechjo/lido-dao/pull/3.
Note that this pull request will merge to dechjo/oracle-v2 branch, when approved. I made it so for ease or reviewing.

**Comment by dechjo** [comment]
Implemented as https://github.com/dechjo/lido-dao/pull/4, please have a look.
