### ISSUE TITLE
Ability to call arbitrary functions after the `reportBeacon` call.

### ISSUE THREAD

**Issue by dechjo** [lidofinance/lido-dao#286]

**Comment by dechjo** [comment]
Should the function be called right after every `reortBeacon` is executed OR after the quorum happened (maybe as a result of `setQuorum` call)? Do we maybe have any specifics for the function to be called (i.e. specific arguments, gas usage, ethers transfer)?
@vshvsh  @ujenjt, what do you think?

**Comment by vshvsh** [comment]
After a successful report to Lido DAO (so after there a quorum, not after every report). 

It should provide the same data as `getLastCompletedReport()` as parameters.

**Comment by dechjo** [comment]
@vshvsh, please advise, who and how often will set this function?
As a draft, I implemented a simple public setter: https://github.com/lidofinance/lido-dao/pull/305/files#diff-6fe7caa502f4e476aef5b7ea5f09cbc22a0cec1b97bf7ff12a816c7f913edeafR158.
