### ISSUE TITLE
Add APR calculation to Oracle contract.

### ISSUE THREAD

**Issue by dechjo** [lidofinance/lido-dao#289]
We need getters that would show a correct APR for stETH stakers.

**Comment by dechjo** [comment]
Briefly discussed here: https://p2p-validator.slack.com/archives/C017VG67EPL/p1612267340045700

**Comment by dechjo** [comment]
> @vshvsh:
> yeah, or in that case, return not the APR but the raw data from the getter: totalPooledEtherBeforeReport, totalPooledEtherAfterReport, reportTimeDelta (edited) 
As I understand here, only the following is needed to report:
- `totalPooledEtherAfterReport` = last commented `beaconBalance` and 
- `reportTimeDelta` = time elapsed since then.
Because `totalPooledEtherBeforeReport` is not yet known to the contract. Am I right?

**Comment by vshvsh** [comment]
> Because `totalPooledEtherBeforeReport` is not yet known to the contract. Am I right?

You are not. `totalPooledEtherBeforeReport` is trivially queried from Lido contract. `totalPooledEtherAfterReport` does not equal `beaconBalance`
