### ISSUE TITLE
Withdrawal spec model

### ISSUE THREAD

**Issue by vshvsh** [lidofinance/lido-dao#336]
We want a smart-contract+beacon chain environment model to develop a model for future implementation.

Rough featureset we want: 

- prove that naive implementations don't work correctly (write a test case which shows that `Simple burn and withdraw` has a `Failure scenario`)

- check how slashing and packed withdrawal queue are combined

- test how it works if the network loses and then restores finality

- test how things work if oracles miss a day or two

- make tests to test-drive the output algorithm

An MVP shouldn't cover all these things, but it should give a framework on which to develop it

Inspiration:

- https://ethresear.ch/t/handling-withdrawals-in-lidos-eth-liquid-staking-protocol/8873
- https://github.com/ethereum/eth2.0-specs - python specs second ether
- ganache, mainnet-fork, brownie
- https://github.com/rocket-pool/beacon-chain-simulator
- https://github.com/lidofinance/modeling

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by TheDZhon** [comment]
The framework was implemented in analytics research and the Lido V2 oracle code.
Closing the issue cause Lido V2 is landed https://github.com/lidofinance/lido-dao/releases/tag/v2.0.0
