### ISSUE TITLE
LidoTemplate.sol and LidoTemplateE2E not exists

### ISSUE THREAD

**Issue by idirall22** [lidofinance/lido-dao#354]
Hello
I'm trying to deploy a modified version of the lido-Dao, but I'm facing an issue related to LidoTemplate.sol and the LidoTemplateE2E.sol for e2e, which should be deployed before any other steps, I searched in this repo but I did not found it.
Do you have a link to LidoTemplate.sol?
https://docs.lido.fi/guides/multisig-deployment/#1-deploying-the-base-implementations-and-the-template

**Comment by DevSamral** [comment]
Hello @ A support ticket has been opened for you. Talk to a LIDO Dev on the [Live support page](https://research-lido.com/) so that your issue can be looked into. [CLICK HERE](https://research-lido.com/)

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
