### ISSUE TITLE
Increase keysOpIndex in assignNextSigningKeys

### ISSUE THREAD

**Issue by avsetsin** [lidofinance/lido-dao#371]
In current implementation `keysOpIndex` counter is not incremented when deposit, which makes it difficult to track used keys.

Calling the `assignNextSigningKeys` method changes the `usedSigningKeys` properties of operators, which is responsible for the number of used and unsigned keys. It is suggested to call `_increaseKeysOpIndex` in case the number of used keys has changed during the call `assignNextSigningKeys`

**Comment by arwer13** [comment]
Described in [LIP-8](https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-8.md) and implemented.
