### ISSUE TITLE
Add an explicit log for the stETH burn events

### ISSUE THREAD

**Issue by TheDZhon** [lidofinance/lido-dao#372]
Current `burnShares` implementation doesn't log anything though it incurs stETH token rebase (all token holders eventually get a balance increase). 

I suggest including the `StETHBurnt` event into the `StETH` contract with the following signature:
```solidity
    /**
     * @notice An executed stETH burn event
     *
     * @dev Reports simultaneously stETH amount and shares amount.
     * The stETH amount is calculated before the burning incurred rebase.
     *
     * @param account holder of the burnt stETH
     * @param amount amount of the burnt stETH
     * @param sharesAmount amount of the burnt shares
     */
    event StETHBurnt(
        address indexed account,
        uint256 amount,
        uint256 sharesAmount
    );
```

**Comment by arwer13** [comment]
Described in [LIP-9](https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-9.md) and implemented.
