### ISSUE TITLE
Add a transfer shares function for `stETH`

### ISSUE THREAD

**Issue by TheDZhon** [lidofinance/lido-dao#376]
`stETH` is a [rebasing token](https://docs.lido.fi/contracts/lido#rebasing). Usually we transfer `stETH` using the `transfer` and `transferFrom` functions which accept as input `stETH` amount, not the amount of the underlying shares.

Sometimes we'd better operate with shares directly to avoid possible rounding issues (the first clear example is [LIP-6 proposal](https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-6.md), see `recoverExcessStETH`).

I propose to include `transferShares` function into the `stETH` contract which accepts shares amount as input, performs actual shares movement from one account to another, and emits `TransferShares` and  `Transfer` events simulteneously.

**Comment by arwer13** [comment]
Described in [LIP-11](https://github.com/lidofinance/lido-improvement-proposals/blob/develop/LIPS/lip-11.md) and implemented.
