### ISSUE TITLE
Automatically check that abi match the code

### ISSUE THREAD

**Issue by ujenjt** [lidofinance/lido-dao#380]
Add a bot/lint checker that do that and check it for each commit

**Comment by dgusakov** [comment]
@ujenjt Great idea. Can you provide details about where the ABIs that we will use for matching is located?

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by dgusakov** [comment]
Resolved by https://github.com/lidofinance/lido-dao/pull/434 and https://github.com/lidofinance/lido-dao/pull/431
