### ISSUE TITLE
Unable to install dependencies on recent Node versions

### ISSUE THREAD

**Issue by kolyasapphire** [lidofinance/lido-dao#381]
On Node 14 everything is fine, but on Node 17 I am unable to install dependencies:

```
YN0009: │ deasync@npm:0.1.24 couldn't be built successfully
YN0000: Failed with errors
```

In Yarn logs for this package install I am getting:

```
Usage Error: Couldn't find a script name "node-gyp" in the top-level (used by deasync@npm:0.1.24)
```

My specs:

```
macOS 12.1 on both M1 and non-Apple processors
Node.js v17.3.1
```

Installing `node-gyp` as a development dependency fixes this.

However, since it's probably an issue with the dependency itself ([issue](https://github.com/abbr/deasync/issues/155)) and we use Yarn, we can overcome this in `.yarnrc.yml`:

```
packageExtensions:
  deasync@*:
    dependencies:
      node-gyp: latest
```

**Comment by DevSamral** [comment]
Hello @ A support ticket has been opened for you. Talk to a LIDO Dev on the [Live support page](https://research-lido.com/) so that your issue can be looked into. [CLICK HERE](https://research-lido.com/)

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
