### ISSUE TITLE
Please support Trezor

### ISSUE THREAD

**Issue by martin-braun** [lidofinance/lido-dao#403]
I'm not sure if this is the right place to request a feature, so please redirect my issue if this is the wrong place. 

Lido looks like a solid secure way to stake in pools since it is open-source. I also like that Ledger is supported, but it is not open-source. [Trezor on the other hand is](https://github.com/trezor/trezor-firmware), so it would be nice if Trezor could be supported by Lido as well.

Thank you!

**Comment by kadmil** [comment]
Hey-hey! UI lives in another repo. Trezor support would def be a good thing to have, but the timing heavily depends on the frontend team workload — you always don't have enough hands and hours in the day.

**Comment by Bleujj1** [comment]
I can help you with whatever issue you have

**Comment by DevSamral** [comment]
Hello @ A support ticket has been opened for you. Talk to a LIDO Dev on the [Live support page](https://research-lido.com/) so that your issue can be looked into. [CLICK HERE](https://research-lido.com/)

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/
