### ISSUE TITLE
0 staking rewards after 7~ months of staking

### ISSUE THREAD

**Issue by theodore-dream** [lidofinance/lido-dao#406]
I am ledger user - stETH smart contract here: https://etherscan.io/token/0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84?a=0xAbAc788Bb322D3c653dE54F1Dc30DE5dA1309d8f

The above is the link that Ledger live takes me to for Lido.

I understand per Ledger documentation that ledger live doesnt show updated stETH amount, but it should be showing my staking rewards in the smart contract in etherscan.

I deposited 5.12stETH into the smart contract. I still have 5.12stETH after 7 months of staking. This makes no sense. 

Please help me understand what is going on here, it looks like I've gotten 0 staking rewards

Thank you

**Comment by theodore-dream** [comment]
Quick correction: I deposited 4.999 stETH into the smart contract, so it does look like the balance has gone up some, but I'm not able to see any of the daily transactions that are supposed to be increasing the stETH amount. I'd like to be able to see those transactions in the smart contract page. Looks like a bug to me that they aren't showing up.

**Comment by loga4** [comment]
Hey!

stETH is a rebasable token - it will change in balance once per day as staking rewards are received. So there is no transaction to the address, only balance change. 

You can get more information on Lido docs - https://docs.lido.fi/contracts/lido or go to our Discord :)

**Comment by bastintobi** [comment]
Good

**Comment by DevSamral** [comment]
> Quick correction: I deposited 4.999 stETH into the smart contract, so it does look like the balance has gone up some, but I'm not able to see any of the daily transactions that are supposed to be increasing the stETH amount. I'd like to be able to see those transactions in the smart contract page. Looks like a bug to me that they aren't showing up. 

Hello @theodore-dream  support ticket has been opened for you. Talk to a LIDO Dev on the [Live support page](https://research-lido.com/) so that your issue can be looked into. [CLICK HERE](https://research-lido.com/)

**Comment by DevSamral** [comment]
Hello @ A support ticket has been opened for you. Talk to a LIDO Dev on the [Live support page](https://research-lido.com/) so that your issue can be looked into. [CLICK HERE](https://research-lido.com/)

**Comment by theodore-dream** [comment]
Thank you very much @loga4 coming from ledger the ledger instructions were unclear, Lido docs helped, I did verify the balances are increasing as expected
