### ISSUE TITLE
Why do we need ILido.sol interface?

### ISSUE THREAD

**Issue by folkyatina** [lidofinance/lido-dao#423]
It looks like:
- it's inconsistent rn (contains some methods from StETH)
- doubles the number of docs (makes it harder to support)
- makes it more difficult to read Lido.sol (because you need to peek into ILido from time to time)

Should we get rid of it, like we did with IStETH.sol

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by TheDZhon** [comment]
Resolved in #482
