### ISSUE TITLE
Single stETH rebasing limit

### ISSUE THREAD

**Issue by TheDZhon** [lidofinance/lido-dao#428]
There is a discussion was introduced previously on the purpose of rebase-incurred sandwich-like *arbitrageability*: #405 

The merge-ready protocol has separate limit enforcement levers to make these arbitrages unprofitable.
It was discussed on the Lido research forum that it's better to enforce the overall rebasing limit via a single number (and, effectively, using the single lever): https://research.lido.fi/t/announcement-merge-ready-protocol-service-pack/2184/8

The issue is here to pick up the idea while designing the next major protocol upgrade (I believe that it should be `withdrawals-enabled protocol` expected to happen with [Capella](https://github.com/ethereum/consensus-specs/issues/2758) or later)

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by TheDZhon** [comment]
Resolved in #482

**Comment by TheDZhon** [comment]
Decided to re-open because V2 isn't deployed on mainnet yet.

**Comment by TheDZhon** [comment]
Resolved in https://github.com/lidofinance/lido-dao/releases/tag/v2.0.0
