### ISSUE TITLE
handleOracleReport doesn't emit events on state change

### ISSUE THREAD

**Issue by bulbozaur** [lidofinance/lido-dao#429]
handleOracleReport(uint256 _beaconValidators, uint256 _beaconBalance) sets `BEACON_BALANCE_POSITION` and `BEACON_VALIDATORS_POSITION` slot but don't emit events on this changes
in case of negative rebase it will update storage, but won't emit any events at all.

https://github.com/lidofinance/lido-dao/blob/08436ce13d67501fa723169c1dc69fe47b90cde4/contracts/0.4.24/Lido.sol#L487-L488

**Comment by Supportsteam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by TheDZhon** [comment]
Resolved in #482

**Comment by TheDZhon** [comment]
Decided to re-open because V2 isn't deployed on mainnet yet.

**Comment by TheDZhon** [comment]
Resolved in https://github.com/lidofinance/lido-dao/releases/tag/v2.0.0
