### ISSUE TITLE
Store address of Deposit Security Module inside Lido

### ISSUE THREAD

**Issue by ujenjt** [lidofinance/lido-dao#435]
* remove permission support for deposit which is potentially would allow deposits for several entities
* add view method for fetch DSM for tooling needs

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by TheDZhon** [comment]
Lido V2 introduced a swiss-knife tool to implement in one fell swoop: [LidoLocator](https://github.com/lidofinance/lido-dao/blob/feature/shapella-upgrade/contracts/0.8.9/LidoLocator.sol)

**Comment by TheDZhon** [comment]
Decided to re-open because V2 isn't deployed on mainnet yet.

**Comment by TheDZhon** [comment]
Hey @0xMySt1c 
Both options are good, would prefer to use LidoLocator though

**Comment by TheDZhon** [comment]
https://github.com/lidofinance/lido-dao/releases/tag/v2.0.0
