### ISSUE TITLE
Add `permit` support for stETH

### ISSUE THREAD

**Issue by TheDZhon** [lidofinance/lido-dao#440]
`stETH`, as an ERC-20 conformant token, has support for allowances management (`approve` and `transferFrom`).
`wstETH`, as a wrapper token for `stETH`, also has support for [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612) (aka `permit`).

For the sake of better composability and design consistency, it's better to implement `permit` also for `stETH` itself.

**Comment by Skytokenn** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14334663/

**Comment by TheDZhon** [comment]
The implementation of this is tricky for the current (0.4.24) solidity version of `stETH`. 

**Technical background**
To correctly implement the ERC-2612 standard, one needs to access the [`CHAINID`](https://www.evm.codes/#46?fork=merge) opcode which was introduced as an assembly function since 0.5.x. Therefore, the possible implementation should be dependent on the externally compiled code (as a library or an external contract, for example) with a more recent solidity version.

**Comment by TheDZhon** [comment]
The issue has been resolved in Lido V2 (see #482). Apart from this, [ERC-1271](https://eips.ethereum.org/EIPS/eip-1271) is also available for `stETH.permit`.

**Comment by TheDZhon** [comment]
Decided to re-open because V2 isn't deployed on mainnet yet.

**Comment by TheDZhon** [comment]
Resolved in https://github.com/lidofinance/lido-dao/releases/tag/v2.0.0
