### ISSUE TITLE
how to upgrade lido app and nos app

### ISSUE THREAD

**Issue by bxlkm** [lidofinance/lido-dao#461]
Multisig app upgrade doc no corresponding script，./scripts/multisig/15-vote-new-app-impl.js non-existent。
Please provide the upgrade steps。
thanks！！！

**Comment by sgilflores3** [comment]
> Multisig app upgrade doc no corresponding script，./scripts/multisig/15-vote-new-app-impl.js non-existent。
> 
> Please provide the upgrade steps。
> 
> thanks！！！
> 
>

**Comment by TheDZhon** [comment]
The Lido V2 protocol brings lots of differences in the deployment.
Please keep an eye on the following branch #665 if it's still relevant
