### ISSUE TITLE
Add a view method in NOR to get a range of keys 

### ISSUE THREAD

**Issue by avsetsin** [lidofinance/lido-dao#475]
The `getSigningKey` method is now used to fetch node operator keys, which can fetch them only one at a time, causing some complexity on the tooling side. I propose to add a method that takes `operator_id`, `from_index` and `to_index` as arguments and returns an array of keys

**Comment by rkolpakov** [comment]
It's now implemented at [this commit](https://github.com/lidofinance/lido-dao/commit/2503d75d9d8b8812b62b9d494db8f81c522ffc54).

**Comment by TheDZhon** [comment]
Resolved in https://github.com/lidofinance/lido-dao/releases/tag/v2.0.0
