### ISSUE TITLE
Unproven keys can be used for the deposit if a node operator has stopped validators

### ISSUE THREAD

**Issue by avsetsin** [lidofinance/lido-dao#478]
When selecting keys, `assignNextSigningKeys` counts the current NO's stake as `usedSigningKeys - stoppedValidators` and checks that the resulting stake <= `stakingLimit`. Therefore keys above the `stakingLimit` in an amount not exceeding `stoppedValidators` can be used for the deposit. The issue is that these keys at the time of deposit have not yet been approved by the DAO.

https://github.com/lidofinance/lido-dao/blob/df95e563445821988baf9869fde64d86c36be55f/contracts/0.4.24/nos/NodeOperatorsRegistry.sol#L351-L352

Related issue: https://github.com/lidofinance/lido-dao/issues/141

**Comment by rkolpakov** [comment]
Due to shapella upgrade implementation of the keys counting will be [changed](https://github.com/lidofinance/lido-dao/blob/staking_router/contracts/0.4.24/nos/NodeOperatorsRegistry.sol#L111) so this mechanic is no longer dangerous.
