### ISSUE TITLE
Alternating transactions of oracle committee members

### ISSUE THREAD

**Issue by avsetsin** [lidofinance/lido-dao#492]
The oracle daemon contains rotation logic, which sequentially adds a delay for some participants. Alternating transactions from participants allows the dev team to see on-chain if one of the participants has stopped sending reports.

I propose to move this logic on-chain to the `CommitteeQuorum.sol` contract as a view method that returns an array of the quorum size of members having priority to report in the current frame. The delay itself should be implemented in the daemon. The method will simplify obtaining a list of participants who are supposed to report to a specific frame when investigating incidents and simplify scripting additional alerts that would match prioritized participants against actual participants.

**Comment by TheDZhon** [comment]
My general consideration here is that this kind of view would have required additional on-chain logic without providing any kind of strong guarantee. This report's priority isn't specified and required currently, and actual transactions are still subject to be affected by the order of inclusion in mempool.

I see three takeaways to push this discussion forward to a more suitable outcome:
- define ordering requirements or at least policies for oracle committee participants
- put this piece of spare parts somewhere else (e.g., subgraph or IDK)
- redefine this one not as a priority thing, but as a cached stats item at least

**Comment by TheDZhon** [comment]
Initial discussion converged to the decision of implementing this one as a part of the upcoming protocol upgrade :+1:

**Comment by TheDZhon** [comment]
Fixed in #563

**Comment by TheDZhon** [comment]
Decided to re-open because V2 isn't deployed on mainnet yet.

**Comment by TheDZhon** [comment]
Resolved in https://github.com/lidofinance/lido-dao/releases/tag/v2.0.0
