### ISSUE TITLE
Slippage control upon withdrawals

### ISSUE THREAD

**Issue by Rassska** [lidofinance/lido-dao#694]
Hey there, hope you're doing fine! 

Do I get it right, that the current version of the [feature/shapella-upgrade](https://github.com/lidofinance/lido-dao/tree/feature/shapella-upgrade) doesn't provide any opportunity for users to set the desired slippage on-chain upon withdrawals? 

Thanks!

**Comment by Rassska** [comment]
Actually, I got it, in the context of the Lido withdrawals it doesn't make any sense.

**Comment by Rassska** [comment]
But wait, what if the following sequence of actions happens? 

- Bob requests a withdrawal of 1e18 stETH. <-- Tx1
- AccountingOracle reports. <-- Tx2
- Let's say the negative rebase happens here (after massive slashing)
- The bunker mode is activated. <-- Tx3

In case of the following sequence of txs, nothing weird happens. But what if the Bob's withdrawal request comes right after AccountingOracle's report(which will report negative rebase) in the same block? In this case, the bunker mode is not activated yet, but it seems Bob losses some funds.

**Comment by Rassska** [comment]
Anyways, I think it's better to have some slippage control mechanism for unexpected cases like that.

**Comment by TheDZhon** [comment]
Hey, @Rassska 

The current architecture presumes strict FIFO ordering of finalization, and requests aren't cancellable.
Based on this, 'virtual slippage' control isn't feasible for implementation on the protocol's level.

To overcome the issue, one might want to exchange stETH for ETH on secondary markets or sell the already placed request position represented as an ERC721-compatible token (NFT).

**Comment by Rassska** [comment]
Of course, the probability for such case is pretty low, but as I got it correctly it makes some sense: 
I'm talking about the following txs order: 
- tx2, 
- tx1, 
- tx3. 

As a result, after 36 days or when bunker mode is de-ativated and the batch which contains Bob's withdrawal is finalized, Bob receives less amount of ETH. 

I mean, the whole concept here is to explore some withdrawal requests passed right after negative rebase happens.

Anyways, thanks a lot, I'm just exploring the Lido for fun!

**Comment by TheDZhon** [comment]
I see your point, yet the bunker mode activates retroactively, lowering probability of the bunker mode activation front-running

see the 'Withdrawal requests finalization' section
https://docs.google.com/document/d/1NoJ3rbVZ1OJfByjibHPA91Ghqk487tT0djAf6PFu8s8/edit

![image](https://user-images.githubusercontent.com/961317/226250139-47a8c42a-3f8f-4e49-a80f-7cd171876508.png)

**Comment by Rassska** [comment]
Thanks a lot, gotcha!
