### ISSUE TITLE
Gas optimizations for deposit process

### ISSUE THREAD

**Issue by vshvsh** [lidofinance/lido-dao#82]
Currently, the submit function, compiled with 200 optimizer iterations, consumes around 577000 gas plus 107000 gas for each registered validator, so the default limit is set by deploy scripts to 16 validators to make the submit transaction occupy no more than 20% of a block. See this file for the related calculations; you can run them with yarn estimate-deposit-loop-gas.

That is on average 130k+ gas per validation key in a batch of 16, about twice as much as a simple deposit. We might find a way to make this number lower.

Note: Switching to the official Deposit contract #88 will impact the numbers mentioned above

**Comment by ujenjt** [comment]
Fixed in #107 and #225
